version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: my-app
    ports:
      - '3080:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: bash -c "npm start"
